### ISSUE TITLE
auto-tools breaks relations

### ISSUE THREAD

**Issue by drkludge** [mapbox/auto-tools#11]
The MapBox effort to add [Phoenix lane counts](https://github.com/mapbox/mapping/issues/180#issuecomment-240295557) removed a number of ways from relations.  I believe auto-tools/knife or the process is at the root cause of the problem.  Auto-tools needs to carry the relation(s) to the new way that is created.

**Comment by planemad** [comment]
@samely can you confirm the issue is not with auto tools?

**Comment by samely** [comment]
@planemad  
@Rub21  and I have split ways with relations, looking for any possible breaking but we didn't find any.
This is the way that knife tool in auto-tools is working. 

![gif](https://cloud.githubusercontent.com/assets/10425629/17780694/ecf57600-6531-11e6-95eb-6e5c0fdbf46e.gif)
