### ISSUE TITLE
Select way after split

### ISSUE THREAD

**Issue by planemad** [mapbox/auto-tools#3]
Tried the plugin and it works great!

We can reduce one more click by auto selecting the way that we will be tagging turn lanes to.

This may not be very easy since we need to guess in which direction to add the turn lane. Ideas:
- Select smaller of the selected way
- Select way in the direction of the closest intersection 

Not sure if this is possible?

cc @samely @Rub21 @abhisheksaikia

**Comment by abhisheksaikia** [comment]
> - Select smaller of the selected way
> - Select way in the direction of the closest intersection

@planemad ^^ `Select the way in the direction of the closest intersection` seems to the safest segment to auto select (if it is possible), as invariably the turn lanes end in an intersection.

Great work @Rub21 @samely 🚀

**Comment by samely** [comment]
@planemad @abhisheksaikia I can work on this to follow a pattern to select a way based on the direction of the road, so we can try how this works.

**Comment by samely** [comment]
@Rub21 @planemad @abhisheksaikia 

I modified the plugin, so it selects the most probable way to be tagged, based on the way length and the number of references of the first or last node.

Closing

**Comment by jothirnadh** [comment]
@samely @Rub21 tried the auto select option, it's getting confused in case of junctions like below.

![knife_tool](https://cloud.githubusercontent.com/assets/8401827/15389561/324d120c-1dd5-11e6-8218-2dd2a74de34b.gif)

cc:/ @planemad

**Comment by samely** [comment]
@jothirnadh I've already improved the accuracy of auto-selection. If you have more cases like this, please, share it.
